apiVersion: apps/v1
kind: Deployment
metadata:
  name: videol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videol
  template:
    metadata:
      labels:
        app: videol
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: videol
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/LandingStartups-html.zip"
        - name: Vless_UUID
          value: "2c075f41-370f-47bd-875e-5cf42b442313"
        - name: Vless_Path
          value: "/2c075f41"
        - name: Vmess_UUID
          value: "5a1ce1bf-1111-4709-87e7-57536402be94"
        - name: Vmess_Path
          value: "/5a1ce1bf"
        - name: Share_Path
          value: "/v2link"
