apiVersion: apps/v1
kind: Deployment
metadata:
  name: videol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videol
  template:
    metadata:
      labels:
        app: videol
    spec:
      containers:
      - image: okteto.dev/videol:latest
        name: videol
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/LandingStartups-html.zip"
        - name: Vless_UUID
          value: "321c8fc7-7359-4af9-b3d8-8c9d35b70780"
        - name: Vless_Path
          value: "/321c8fc7"
        - name: Vmess_UUID
          value: "ba2e4ba6-5ef3-49e1-9191-2b8eff6720a4"
        - name: Vmess_Path
          value: "/ba2e4ba6"
        - name: Share_Path
          value: "/v2link"
